language: java

sudo: false
dist: trusty

os:
- linux
- osx

jdk:
- openjdk8
- openjdk11
- openjdk-ea

matrix:
  exclude: # Not jet supported https://sormuras.github.io/blog/2018-05-31-jdk-matrix.html
  - os: osx
    jdk: openjdk8
  - os: osx
    jdk: oraclejdk8
  - os: osx
    jdk: oraclejdk11
  - os: osx
    jdk: oraclejdk-ea
