trigger: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      options: "-PjavaCompatibility=11"
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'javadoc'
  - bash: .ci/publishJavadoc.sh
    env:
      GITHUB_USERNAME: $(GITHUB_USERNAME)
      GITHUB_TOKEN: $(GITHUB_TOKEN)
